# Generated by Django 3.1.2 on 2020-10-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20201005_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsrvproject',
            name='haveToken',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
