# Generated by Django 3.1.2 on 2020-11-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20201030_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsrvproject',
            name='timeLimit',
            field=models.IntegerField(default=0),
        ),
    ]
