# Generated by Django 3.1.2 on 2020-12-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20201212_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='addTime',
            new_name='timestamp',
        ),
    ]
