# Generated by Django 3.1.2 on 2020-12-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_problemsubmition'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsubmition',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
