# Generated by Django 3.1.4 on 2020-12-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20201213_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memoryLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='timeLimit',
            field=models.IntegerField(default=0),
        ),
    ]
