# Generated by Django 3.1.4 on 2020-12-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20201214_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='memoryLimit',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='timeLimit',
        ),
        migrations.AddField(
            model_name='problem',
            name='timeUsed',
            field=models.FloatField(default=0),
        ),
    ]
