# Generated by Django 3.1.4 on 2020-12-16 23:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20201216_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='detail',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
