# Generated by Django 3.1.4 on 2020-12-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20201216_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmission',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='database.contest'),
        ),
    ]
