# Generated by Django 3.1.4 on 2020-12-26 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20201217_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='timeUp',
        ),
        migrations.AlterField(
            model_name='problemhighestscore',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestScore', to='database.contest'),
        ),
        migrations.AlterField(
            model_name='problemhighestscore',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestScore', to='database.team'),
        ),
        migrations.AlterField(
            model_name='problemhighestscore',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestScore', to=settings.AUTH_USER_MODEL),
        ),
    ]
