# Generated by Django 3.1.4 on 2021-01-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_auto_20201226_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='withTeam',
        ),
        migrations.AlterField(
            model_name='problemsubmission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='database.contest'),
        ),
    ]
