# Generated by Django 3.1.4 on 2021-01-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_auto_20210102_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemsubmission',
            name='contest',
        ),
        migrations.AddField(
            model_name='problemsubmission',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.team'),
        ),
    ]
