# Generated by Django 3.1.4 on 2021-01-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_auto_20210102_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsubmission',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.team'),
        ),
    ]
