# Generated by Django 3.1.4 on 2021-01-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_auto_20210102_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemhighestscore',
            name='contest',
        ),
        migrations.AlterField(
            model_name='problemhighestscore',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestScore', to='database.problem'),
        ),
    ]
