# Generated by Django 3.1.4 on 2021-02-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_auto_20210131_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemjudgedetail',
            name='memoryUsed',
            field=models.IntegerField(default=0),
        ),
    ]
