# Generated by Django 3.1.4 on 2021-02-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_game_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebotscore',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='database.gamebot'),
        ),
    ]
