# Generated by Django 3.1.4 on 2021-02-05 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0049_auto_20210204_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameai',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai', to='database.team'),
        ),
        migrations.AlterField(
            model_name='gameai',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai', to=settings.AUTH_USER_MODEL),
        ),
    ]
