# Generated by Django 3.1.4 on 2021-02-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_gamebot_compilestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamebotplay',
            old_name='deltaScore',
            new_name='deltaRankingScore',
        ),
        migrations.AddField(
            model_name='gameai',
            name='playerNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamebot',
            name='programPath',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='gamebot',
            name='ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamebot',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamebotplay',
            name='oldRankingScore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='database.game'),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamebotplay',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='botplay', to='database.gamebot'),
        ),
        migrations.AlterField(
            model_name='gamebotplay',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='botplay', to='database.gamerecord'),
        ),
        migrations.DeleteModel(
            name='GameBotScore',
        ),
    ]
