# Generated by Django 3.1.4 on 2021-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_auto_20210207_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameai',
            name='playerNumber',
        ),
        migrations.AddField(
            model_name='game',
            name='playerNumber',
            field=models.IntegerField(default=0),
        ),
    ]
