# Generated by Django 3.0.2 on 2021-10-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0054_auto_20210207_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebot',
            name='addition',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
