# Generated by Django 3.0.2 on 2021-10-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_auto_20211010_1534'),
        ('database', '0055_auto_20211010_1511'),
    ]

    operations = [
    ]
