# Generated by Django 3.2.15 on 2022-10-25 20:57

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_auto_20221023_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(null=True, upload_to=database.models.Mt_dirpath),
        ),
    ]
