# Generated by Django 3.2.15 on 2022-12-03 21:31

import database.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_mcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('file', models.FileField(blank=True, null=True, upload_to=database.models.Mt_dirpath)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.material')),
            ],
        ),
    ]
