# Generated by Django 3.2.15 on 2022-12-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0064_alter_mcomment_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcomment',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.material'),
        ),
    ]
