# Generated by Django 3.2.15 on 2022-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_alter_mcomment_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
