# Generated by Django 3.2.15 on 2022-12-11 15:36

from django.db import migrations


def transfer_files(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Material = apps.get_model('database', 'Material')
    MFile = apps.get_model('database', 'MFile')

    for material in Material.objects.all():
        if material.file:
            title = material.title # material_00001.zip
            author = material.author
            timestamp = material.timestamp
            file = material.file
            MFile.objects.create(
                title = title,
                author = author,
                timestamp = timestamp,
                file = file,
                material = material
            )


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_mfile_timestamp'),
    ]

    operations = [
        migrations.RunPython(transfer_files),
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
    ]
